/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.sun.xml.internal.ws.util.StringUtils;
import includes.DatabaseConnection;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Client
 */
public class AutoriRadovi extends javax.swing.JFrame {
    private Connection conn;
    private int autori_radovi_id;
    
    String autor_id, rad_id;
    
    public AutoriRadovi() {
        initComponents();
        DatabaseConnection dbc = DatabaseConnection.getDatabaseConnection();
            conn = dbc.getConnection();
            setTableData();
            
            try {
                String queryString = "SELECT * from autori";
                Statement smt = conn.createStatement();
                ResultSet resultSet = smt.executeQuery(queryString);
                ResultSetMetaData metaData = resultSet.getMetaData();
                int colCount = metaData.getColumnCount();
                while(resultSet.next())
                {
                    cbAutori.addItem(resultSet.getString(2).concat(" ").concat(resultSet.getString(3)));
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
             
            try {
                String queryString = "SELECT * from radovi";
                Statement smt = conn.createStatement();
                ResultSet resultSet = smt.executeQuery(queryString);
                ResultSetMetaData metaData = resultSet.getMetaData();
                int colCount = metaData.getColumnCount();
                while(resultSet.next())
                {
                    cbRad.addItem(resultSet.getString(2));
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }
    
    int idRad(String naziv)
    {
        int id = 0;
        try {
            String queryString = "SELECT rad_id from radovi where radovi.naziv = '"+naziv+"'";
            Statement smt = conn.createStatement();
            ResultSet resultSet = smt.executeQuery(queryString);
            if(resultSet.next())
                id = resultSet.getInt("rad_id");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        return id;
    }
    
    String nazivRada(int id)
    {
        String naziv = "";
        try {
            String queryString = "SELECT naziv from radovi where radovi.rad_id = "+id;
            Statement smt = conn.createStatement();
            ResultSet resultSet = smt.executeQuery(queryString);
            if(resultSet.next())
                naziv = resultSet.getString("naziv");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        return naziv;
    }
    
     String nazivAutora(int id)
    {
        String naziv = "";
        try {
            String queryString = "SELECT ime, prezime from autori where autori.autor_id = "+id;
            Statement smt = conn.createStatement();
            ResultSet resultSet = smt.executeQuery(queryString);
            if(resultSet.next())
                naziv = resultSet.getString("ime").concat(" ").concat(resultSet.getString("prezime"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        return naziv;
    }
     
    int idAutora(String naziv)
    {
        String[] splited = naziv.split("\\s+");

        int id = 0;
        try {
            String queryString = "SELECT autor_id from autori where autori.ime = '"+splited[0]+"' AND autori.prezime = '"+splited[1]+"'";
            Statement smt = conn.createStatement();
            ResultSet resultSet = smt.executeQuery(queryString);
            if(resultSet.next())
                id = resultSet.getInt("autor_id");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbAutori = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbRad = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        radRecezentTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodavanje autora za rad"));
        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 15, 15));

        jLabel7.setText("Izaberite autora:");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);

        jPanel1.add(cbAutori);

        jLabel8.setText("Izaberite rad:");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);

        jPanel1.add(cbRad);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        btnAdd.setText("Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnUpdate.setText("Ažuriraj");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnDelete.setText("Izbriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);

        btnReset.setText("Resetuj");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        radRecezentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        radRecezentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radRecezentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(radRecezentTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        jButton1.setText("Vrati se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
           
        Object objAutor = cbAutori.getSelectedItem();
        autor_id = objAutor.toString();
        
        Object objRad = cbRad.getSelectedItem();
        rad_id = objRad.toString();
        
        System.out.println(autor_id+" "+rad_id);
          
        if(autor_id != null && rad_id != null)
            {
                try {
                    Statement smt = conn.createStatement();
                    smt.execute("insert into autori_radovi(rad_id, autor_id) "
                    + "values('"+idRad(rad_id)+"', '"+idAutora(autor_id)+"')");
                JOptionPane.showMessageDialog(this, "Uspjesno dodano");
                smt.close();
                setTableData();
                resetData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Molimo popunite sva polja!");
            }
         
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       resetData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void radRecezentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radRecezentTableMouseClicked
        try {
            autori_radovi_id = Integer.parseInt(radRecezentTable.getValueAt(radRecezentTable.getSelectedRow(), 0).toString());
            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery("select * from autori_radovi where autori_radovi_id ="+autori_radovi_id);
            if(rs.next()) {
                cbRad.setSelectedIndex(rs.getInt(2)-1);
                cbAutori.setSelectedIndex(rs.getInt(3)-1);
            }
            rs.close();
            smt.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_radRecezentTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(autori_radovi_id != 0)
        {
            Object objAutor = cbAutori.getSelectedItem();
            autor_id = objAutor.toString();

            Object objRad = cbRad.getSelectedItem();
            rad_id = objRad.toString();
            System.out.println(idAutora(autor_id)+" "+idRad(rad_id));
            try {
                Statement smt = conn.createStatement();
                smt.executeUpdate("update autori_radovi set rad_id="+idRad(rad_id)+", autor_id="+idAutora(autor_id)+" where autori_radovi_id="+autori_radovi_id);
                JOptionPane.showMessageDialog(this, "Autor rada azuriran");
                setTableData();
                resetData();
                autori_radovi_id = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ne moze se azurirati zapis..."+" "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       if(autori_radovi_id != 0) 
        {
            try {
               Statement smt = conn.createStatement(); 
               smt.execute("delete from autori_radovi where autori_radovi_id = "+autori_radovi_id);
               JOptionPane.showMessageDialog(this, "Autor rada uspješno izbrisan");
               setTableData();
               resetData();
               autori_radovi_id = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Zapis se ne moze izbrisati... "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        MainMenu mainMenu = new MainMenu();
        mainMenu.setDefaultCloseOperation(MainMenu.DISPOSE_ON_CLOSE);
        mainMenu.setSize(800, 600);
        mainMenu.setLocationRelativeTo(null);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetData() {
        /*tfDatumSlanja.setText("");
        tfDatumDobijanja.setText("");*/
    }
    private void setTableData() {
        try {
            int rows = 0;
            int rowIndex = 0;
            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery("select * from autori_radovi order by autori_radovi_id desc");
            if (rs.next()) {
                rs.last();
                rows = rs.getRow();
                rs.beforeFirst();
            }
            
            String[][] data = new String[rows][3];
            while(rs.next())
            {
                data[rowIndex][0] = rs.getInt(1)+"";
                data[rowIndex][1] = nazivRada(rs.getInt(2));
                data[rowIndex][2] = nazivAutora(rs.getInt(3));
                rowIndex++;
            }
            String[] cols = {"ID", "Rad", "Autor"};
            DefaultTableModel model = new DefaultTableModel(data, cols);
            radRecezentTable.setModel(model);
            
            rs.close();
            smt.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ne mogu se popuniti podaci..."+ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbAutori;
    private javax.swing.JComboBox<String> cbRad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable radRecezentTable;
    // End of variables declaration//GEN-END:variables
}
