/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import includes.DatabaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Client
 */
public class Casopisi extends javax.swing.JFrame {
    private Connection conn;
    private int casopis_id;
    
    String naziv, urednik;
    int broj_izlazaka, godina_osnivanja, broj_osoba_redakcije;
            
    public Casopisi() {
        initComponents();
        DatabaseConnection dbc = DatabaseConnection.getDatabaseConnection();
            conn = dbc.getConnection();
            setTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfBrojIzlazaka = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfGodinaOsnivanja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfUrednik = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfUkupanBrojRedakcije = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        casopisTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Casopisi"));
        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 10, 20));

        jLabel1.setText("Naziv:");
        jPanel1.add(jLabel1);

        tfNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNazivActionPerformed(evt);
            }
        });
        jPanel1.add(tfNaziv);

        jLabel2.setText("Broj izlazaka:");
        jPanel1.add(jLabel2);
        jPanel1.add(tfBrojIzlazaka);

        jLabel3.setText("Godina osnivanja:");
        jPanel1.add(jLabel3);
        jPanel1.add(tfGodinaOsnivanja);

        jLabel4.setText("Urednik:");
        jPanel1.add(jLabel4);

        tfUrednik.setToolTipText("");
        jPanel1.add(tfUrednik);

        jLabel5.setText("Ukupan broj redakcije:");
        jPanel1.add(jLabel5);
        jPanel1.add(tfUkupanBrojRedakcije);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        btnAdd.setText("Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnUpdate.setText("Ažuriraj");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnDelete.setText("Izbriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);

        btnReset.setText("Resetuj");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        casopisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        casopisTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casopisTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(casopisTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        jButton2.setText("Vrati se");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNazivActionPerformed

      
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
           
        naziv = tfNaziv.getText();
        urednik = tfUrednik.getText();
        broj_izlazaka = Integer.parseInt(tfBrojIzlazaka.getText());
        godina_osnivanja = Integer.parseInt(tfGodinaOsnivanja.getText());
        broj_osoba_redakcije = Integer.parseInt(tfUkupanBrojRedakcije.getText());
        
        if(!naziv.isEmpty() && !urednik.isEmpty() && broj_izlazaka > 0)
            {
                try {
                    Statement smt = conn.createStatement();
                    smt.execute("insert into casopisi(naziv, broj_izlazaka, godina_osnivanja, urednik, broj_osoba_redakcije) "
                    + "values('"+naziv+"', '"+broj_izlazaka+"', '"+godina_osnivanja+"', '"+urednik+"', '"+broj_osoba_redakcije+"')");
                JOptionPane.showMessageDialog(this, "Uspjesno dodano");
                smt.close();
                setTableData();
                resetData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Molimo popunite sva polja!");
            }
         
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       resetData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void casopisTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casopisTableMouseClicked
        try {
            casopis_id = Integer.parseInt(casopisTable.getValueAt(casopisTable.getSelectedRow(), 0).toString());
            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery("select * from casopisi where casopis_id ="+casopis_id);
            if(rs.next()) {
                tfNaziv.setText(rs.getString(2));
                tfBrojIzlazaka.setText(rs.getInt(3)+"");
                tfGodinaOsnivanja.setText(rs.getInt(4)+"");
                tfUrednik.setText(rs.getString(5));
                tfUkupanBrojRedakcije.setText(rs.getInt(6)+"");
            }
            rs.close();
            smt.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_casopisTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(casopis_id != 0)
        {
            naziv = tfNaziv.getText();
            urednik = tfUrednik.getText();
            broj_izlazaka = Integer.parseInt(tfBrojIzlazaka.getText());
            godina_osnivanja = Integer.parseInt(tfGodinaOsnivanja.getText());
            broj_osoba_redakcije = Integer.parseInt(tfUkupanBrojRedakcije.getText());
            try {
                Statement smt = conn.createStatement();
                smt.executeUpdate("update casopisi set naziv='"+naziv+"', urednik='"+urednik+"', broj_izlazaka='"+broj_izlazaka+"', godina_osnivanja='"+godina_osnivanja+"', broj_osoba_redakcije='"+broj_osoba_redakcije+"' where casopis_id="+casopis_id);
                JOptionPane.showMessageDialog(this, "Casopis azuriran");
                setTableData();
                resetData();
                casopis_id = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ne moze se azurirati zapis..."+" "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(casopis_id != 0) 
        {
            try {
               Statement smt = conn.createStatement(); 
               smt.execute("delete from casopisi where casopis_id = "+casopis_id);
               JOptionPane.showMessageDialog(this, "Časopis uspješno izbrisan");
               setTableData();
               resetData();
               casopis_id = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Zapis se ne moze izbrisati... "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        MainMenu mainMenu = new MainMenu();
        mainMenu.setDefaultCloseOperation(MainMenu.DISPOSE_ON_CLOSE);
        mainMenu.setSize(800, 600);
        mainMenu.setLocationRelativeTo(null);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetData() {
        tfNaziv.setText("");
        tfUrednik.setText("");
        tfBrojIzlazaka.setText("");
        tfGodinaOsnivanja.setText("");
        tfUkupanBrojRedakcije.setText("");
    }
    private void setTableData() {
        try {
            int rows = 0;
            int rowIndex = 0;
            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery("select * from casopisi order by casopis_id desc");
            if (rs.next()) {
                rs.last();
                rows = rs.getRow();
                rs.beforeFirst();
            }
            
            String[][] data = new String[rows][6];
            while(rs.next())
            {
                data[rowIndex][0] = rs.getInt(1)+"";
                data[rowIndex][1] = rs.getString(2);
                data[rowIndex][2] = rs.getInt(3)+"";
                data[rowIndex][3] = rs.getInt(4)+"";
                data[rowIndex][4] = rs.getString(5);
                data[rowIndex][5] = rs.getInt(6)+"";
                rowIndex++;
            }
            String[] cols = {"ID", "Naziv", "Broj izlazaka", "Godina osnivanja", "Urednik", "Broj osoba redakcije"};
            DefaultTableModel model = new DefaultTableModel(data, cols);
            casopisTable.setModel(model);
            
            rs.close();
            smt.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ne mogu se popuniti podaci..."+ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Casopisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Casopisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Casopisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casopisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Casopisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable casopisTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfBrojIzlazaka;
    private javax.swing.JTextField tfGodinaOsnivanja;
    private javax.swing.JTextField tfNaziv;
    private javax.swing.JTextField tfUkupanBrojRedakcije;
    private javax.swing.JTextField tfUrednik;
    // End of variables declaration//GEN-END:variables
}
