
import includes.DatabaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Client
 */
public class Radovi extends javax.swing.JFrame {
    private Connection conn;
    private int rad_id, status, odluka, casopis_id, pocetna_strana, krajnja_strana;
    String naziv, redniBrojIzdavanja, redniBrojGodine;
    java.sql.Date datum_prispeca_recenzije, datum_slanja_recenzije, datum_prispeca_casopisa;
            
    public Radovi() {
        initComponents();
        DatabaseConnection dbc = DatabaseConnection.getDatabaseConnection();
            conn = dbc.getConnection();
            setTableData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        autorTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDatumSlanjaRecenzije = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDatumPrispjecaRecenzije = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDatumPrispjecaCasopisa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfOdluka = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbCasopis = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tfRBrGodine = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfRedniBrIzdavanja = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfPocetnaStrana = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfKrajnjaStrana = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        btnAdd.setText("Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnUpdate.setText("Ažuriraj");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnDelete.setText("Izbriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);

        btnReset.setText("Resetuj");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        autorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        autorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(autorTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new java.awt.GridLayout(6, 4, 5, 10));

        jLabel1.setText("Naziv:");
        jPanel4.add(jLabel1);
        jPanel4.add(tfNaziv);

        jLabel3.setText("Datum slanja recenzije:");
        jPanel4.add(jLabel3);
        jPanel4.add(tfDatumSlanjaRecenzije);

        jLabel4.setText("Datum prispjeća recenzije:");
        jPanel4.add(jLabel4);
        jPanel4.add(tfDatumPrispjecaRecenzije);

        jLabel5.setText("Datum prispjeća časopisa:");
        jPanel4.add(jLabel5);
        jPanel4.add(tfDatumPrispjecaCasopisa);

        jLabel6.setText("Odluka:");
        jPanel4.add(jLabel6);
        jPanel4.add(tfOdluka);

        jLabel7.setText("Časopis:");
        jPanel4.add(jLabel7);

        jPanel4.add(cbCasopis);

        jLabel8.setText("R.br. godine:");
        jPanel4.add(jLabel8);
        jPanel4.add(tfRBrGodine);

        jLabel9.setText("R.br. izdvanja:");
        jPanel4.add(jLabel9);
        jPanel4.add(tfRedniBrIzdavanja);

        jLabel10.setText("Početna strana:");
        jPanel4.add(jLabel10);
        jPanel4.add(tfPocetnaStrana);

        jLabel11.setText("Krajnja strana:");
        jPanel4.add(jLabel11);
        jPanel4.add(tfKrajnjaStrana);

        jButton1.setText("Vrati se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
           
        naziv = tfNaziv.getText();
        odluka = Integer.parseInt(tfOdluka.getText());
//        casopis_id = Integer.parseInt(tfCasopis.getText());
        datum_prispeca_casopisa = java.sql.Date.valueOf(tfDatumPrispjecaCasopisa.getText());
        datum_prispeca_recenzije = java.sql.Date.valueOf(tfDatumPrispjecaRecenzije.getText());
        datum_slanja_recenzije = java.sql.Date.valueOf(tfDatumSlanjaRecenzije.getText());
        krajnja_strana = Integer.parseInt(tfKrajnjaStrana.getText());
        pocetna_strana = Integer.parseInt(tfPocetnaStrana.getText());
        redniBrojGodine = tfRBrGodine.getText();
        redniBrojIzdavanja = tfRedniBrIzdavanja.getText();
        
        /*if(!ime.isEmpty() && !prezime.isEmpty() && !adresa.isEmpty() && !telefon.isEmpty() && !email.isEmpty() && !institucija.isEmpty())
            {
                try {
                    Statement smt = conn.createStatement();
                    smt.execute("insert into autori(ime, prezime, adresa, telefon, email, institucija) "
                    + "values('"+ime+"', '"+prezime+"', '"+adresa+"', '"+telefon+"', '"+email+"', '"+institucija+"')");
                JOptionPane.showMessageDialog(this, "Uspjesno dodano");
                smt.close();
                setTableData();
                resetData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Molimo popunite sva polja!");
            }*/
         
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       resetData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void autorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autorTableMouseClicked
        /*try {
            autor_id = Integer.parseInt(autorTable.getValueAt(autorTable.getSelectedRow(), 0).toString());
            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery("select * from autori where autor_id ="+autor_id);
            if(rs.next()) {
                tfIme.setText(rs.getString(2));
                tfPrezime.setText(rs.getString(3));
                tfAdresa.setText(rs.getString(4));
                tfTelefon.setText(rs.getString(5));
                tfEmail.setText(rs.getString(6));
                tfInstitucija.setText(rs.getString(7));
            }
            rs.close();
            smt.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }*/
    }//GEN-LAST:event_autorTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        /*if(autor_id != 0)
        {
            ime = tfIme.getText();
            prezime = tfPrezime.getText();
            adresa = tfAdresa.getText();
            telefon = tfTelefon.getText();
            email = tfEmail.getText();
            institucija = tfInstitucija.getText();
            
            try {
                Statement smt = conn.createStatement();
                smt.executeUpdate("update autori set ime='"+ime+"', prezime='"+prezime+"', adresa='"+adresa+"', telefon='"+telefon+"', email='"+email+"', institucija='"+institucija+"' where autor_id="+autor_id);
                JOptionPane.showMessageDialog(this, "Autor azuriran");
                setTableData();
                resetData();
                autor_id = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ne moze se azurirati zapis..."+" "+ex.getMessage());
            }
        }*/
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(rad_id != 0) 
        {
            try {
               Statement smt = conn.createStatement(); 
               smt.execute("delete from radovi where rad_id = "+rad_id);
               JOptionPane.showMessageDialog(this, "Rad uspješno izbrisan");
               setTableData();
               resetData();
               rad_id = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Zapis se ne moze izbrisati... "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        MainMenu mainMenu = new MainMenu();
        mainMenu.setDefaultCloseOperation(MainMenu.DISPOSE_ON_CLOSE);
        mainMenu.setSize(800, 600);
        mainMenu.setLocationRelativeTo(null);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetData() {
      /*  tfIme.setText("");
        tfPrezime.setText("");
        tfAdresa.setText("");
        tfTelefon.setText("");
        tfEmail.setText("");
        tfInstitucija.setText("");*/
    }
    private void setTableData() {
        try {
            int rows = 0;
            int rowIndex = 0;
            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery("select * from radovi order by rad_id desc");
            if (rs.next()) {
                rs.last();
                rows = rs.getRow();
                rs.beforeFirst();
            }
            
            String[][] data = new String[rows][7];
            while(rs.next())
            {
                data[rowIndex][0] = rs.getInt(1)+"";
                data[rowIndex][1] = rs.getString(2);
                data[rowIndex][2] = rs.getString(3);
                data[rowIndex][3] = rs.getString(4);
                data[rowIndex][4] = rs.getString(5);
                data[rowIndex][5] = rs.getString(6);
                data[rowIndex][6] = rs.getString(7);
                rowIndex++;
            }
            String[] cols = {"ID", "Ime", "Prezime", "Adresa", "Telefon", "Email", "Institucija"};
            DefaultTableModel model = new DefaultTableModel(data, cols);
            autorTable.setModel(model);
            
            rs.close();
            smt.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ne mogu se popuniti podaci..."+ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable autorTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbCasopis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfDatumPrispjecaCasopisa;
    private javax.swing.JTextField tfDatumPrispjecaRecenzije;
    private javax.swing.JTextField tfDatumSlanjaRecenzije;
    private javax.swing.JTextField tfKrajnjaStrana;
    private javax.swing.JTextField tfNaziv;
    private javax.swing.JTextField tfOdluka;
    private javax.swing.JTextField tfPocetnaStrana;
    private javax.swing.JTextField tfRBrGodine;
    private javax.swing.JTextField tfRedniBrIzdavanja;
    // End of variables declaration//GEN-END:variables
}
