
import includes.DatabaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Client
 */
public class Recezenti extends javax.swing.JFrame {
    private Connection conn;
    private int recezent_id;
    
    String ime, prezime, adresa, telefon, email;
            
    public Recezenti() {
        initComponents();
        DatabaseConnection dbc = DatabaseConnection.getDatabaseConnection();
            conn = dbc.getConnection();
            setTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recezentTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfAdresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        btnAdd.setText("Dodaj");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnUpdate.setText("Ažuriraj");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnDelete.setText("Izbriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);

        btnReset.setText("Resetuj");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        recezentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        recezentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recezentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(recezentTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new java.awt.GridLayout(5, 2, 10, 0));

        jLabel1.setText("Ime:");
        jPanel4.add(jLabel1);

        tfIme.setToolTipText("");
        jPanel4.add(tfIme);

        jLabel2.setText("Prezime:");
        jPanel4.add(jLabel2);
        jPanel4.add(tfPrezime);

        jLabel3.setText("Adresa:");
        jPanel4.add(jLabel3);
        jPanel4.add(tfAdresa);

        jLabel4.setText("Telefon:");
        jPanel4.add(jLabel4);
        jPanel4.add(tfTelefon);

        jLabel5.setText("Email:");
        jPanel4.add(jLabel5);
        jPanel4.add(tfEmail);

        jButton1.setText("Vrati se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
           
        ime = tfIme.getText();
        prezime = tfPrezime.getText();
        adresa = tfAdresa.getText();
        telefon = tfTelefon.getText();
        email = tfEmail.getText();
        
        if(!ime.isEmpty() && !prezime.isEmpty() && !adresa.isEmpty() && !telefon.isEmpty() && !email.isEmpty())
            {
                try {
                    Statement smt = conn.createStatement();
                    smt.execute("insert into recezenti(ime, prezime, adresa, telefon, email) "
                    + "values('"+ime+"', '"+prezime+"', '"+adresa+"', '"+telefon+"', '"+email+"')");
                JOptionPane.showMessageDialog(this, "Uspjesno dodano");
                smt.close();
                setTableData();
                resetData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Molimo popunite sva polja!");
            }
         
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       resetData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void recezentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recezentTableMouseClicked
        try {
            recezent_id = Integer.parseInt(recezentTable.getValueAt(recezentTable.getSelectedRow(), 0).toString());
            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery("select * from recezenti where recezent_id ="+recezent_id);
            if(rs.next()) {
                tfIme.setText(rs.getString(2));
                tfPrezime.setText(rs.getString(3));
                tfAdresa.setText(rs.getString(4));
                tfTelefon.setText(rs.getString(5));
                tfEmail.setText(rs.getString(6));
            }
            rs.close();
            smt.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_recezentTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(recezent_id != 0)
        {
            ime = tfIme.getText();
            prezime = tfPrezime.getText();
            adresa = tfAdresa.getText();
            telefon = tfTelefon.getText();
            email = tfEmail.getText();
            
            try {
                Statement smt = conn.createStatement();
                smt.executeUpdate("update recezenti set ime='"+ime+"', prezime='"+prezime+"', adresa='"+adresa+"', telefon='"+telefon+"', email='"+email+"' where recezent_id="+recezent_id);
                JOptionPane.showMessageDialog(this, "Recezent azuriran");
                setTableData();
                resetData();
                recezent_id = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ne moze se azurirati zapis..."+" "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(recezent_id != 0) 
        {
            try {
               Statement smt = conn.createStatement(); 
               smt.execute("delete from recezenti where recezent_id = "+recezent_id);
               JOptionPane.showMessageDialog(this, "Recezent uspješno izbrisan");
               setTableData();
               resetData();
               recezent_id = 0;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Zapis se ne moze izbrisati... "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        MainMenu mainMenu = new MainMenu();
        mainMenu.setDefaultCloseOperation(MainMenu.DISPOSE_ON_CLOSE);
        mainMenu.setSize(800, 600);
        mainMenu.setLocationRelativeTo(null);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resetData() {
        tfIme.setText("");
        tfPrezime.setText("");
        tfAdresa.setText("");
        tfTelefon.setText("");
        tfEmail.setText("");
    }
    private void setTableData() {
        try {
            int rows = 0;
            int rowIndex = 0;
            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery("select * from recezenti order by recezent_id desc");
            if (rs.next()) {
                rs.last();
                rows = rs.getRow();
                rs.beforeFirst();
            }
            
            String[][] data = new String[rows][6];
            while(rs.next())
            {
                data[rowIndex][0] = rs.getInt(1)+"";
                data[rowIndex][1] = rs.getString(2);
                data[rowIndex][2] = rs.getString(3);
                data[rowIndex][3] = rs.getString(4);
                data[rowIndex][4] = rs.getString(5);
                data[rowIndex][5] = rs.getString(6);
                rowIndex++;
            }
            String[] cols = {"ID", "Ime", "Prezime", "Adresa", "Telefon", "Email"};
            DefaultTableModel model = new DefaultTableModel(data, cols);
            recezentTable.setModel(model);
            
            rs.close();
            smt.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ne mogu se popuniti podaci..."+ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable recezentTable;
    private javax.swing.JTextField tfAdresa;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfIme;
    private javax.swing.JTextField tfPrezime;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
