
import includes.DatabaseConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adnan
 */
public class SpisakRadovaAutora extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    private Connection conn;
    
    String autor_id;
    
    public SpisakRadovaAutora() {
        initComponents();
        DatabaseConnection dbc = DatabaseConnection.getDatabaseConnection();
            conn = dbc.getConnection();
//            setTableData();
            try {
                String queryString = "SELECT * from autori";
                Statement smt = conn.createStatement();
                ResultSet resultSet = smt.executeQuery(queryString);
                ResultSetMetaData metaData = resultSet.getMetaData();
                int colCount = metaData.getColumnCount();
                while(resultSet.next())
                {
                    cbAutor.addItem(resultSet.getString(2).concat(" ").concat(resultSet.getString(3)));
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }
    
    String brojOdobrenih(int id)
    {
        String status = "Nije prihvacen";
        try {
            String queryString = "SELECT SUM(odluka = 1) FROM rad_recezent WHERE rad_id = "+id;
            Statement smt = conn.createStatement();
            ResultSet resultSet = smt.executeQuery(queryString);
            if(resultSet.next())
                id = resultSet.getInt(1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        if(id > 2)
            status = "Prihvacen";
        return status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbAutor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        spisakRadovaAutora = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Vrati se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Izaberite autora:");

        cbAutor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAutorItemStateChanged(evt);
            }
        });

        spisakRadovaAutora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spisakRadovaAutora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spisakRadovaAutoraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(spisakRadovaAutora);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        MainMenu mainMenu = new MainMenu();
        mainMenu.setDefaultCloseOperation(MainMenu.DISPOSE_ON_CLOSE);
        mainMenu.setSize(800, 600);
        mainMenu.setLocationRelativeTo(null);
        mainMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

      int idAutor(String naziv)
    {
        String[] splited = naziv.split("\\s+");

        int id = 0;
        try {
            String queryString = "SELECT autor_id from autori where autori.ime = '"+splited[0]+"' AND autori.prezime = '"+splited[1]+"'";
            Statement smt = conn.createStatement();
            ResultSet resultSet = smt.executeQuery(queryString);
            if(resultSet.next())
                id = resultSet.getInt("autor_id");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        return id;
    }
      
    private void cbAutorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAutorItemStateChanged
        setTableData();
    }//GEN-LAST:event_cbAutorItemStateChanged

    private void spisakRadovaAutoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spisakRadovaAutoraMouseClicked
        try {
            /*recezent_radovi_id = Integer.parseInt(spisakRadovaRecezenta.getValueAt(spisakRadovaRecezenta.getSelectedRow(), 0).toString());
            Statement smt = conn.createStatement();
            ResultSet rs = smt.executeQuery("select * from rad_recezent where rad_recezent_id ="+recezent_radovi_id);
            if(rs.next()) {
                cbRad.setSelectedIndex(rs.getInt(2)-1);
                cbRecezent.setSelectedIndex(rs.getInt(3)-1);
                cbOdluka.setSelectedIndex(rs.getInt(4));
                tfDatumSlanja.setText(rs.getString(5));
                tfDatumDobijanja.setText(rs.getString(6));
            }
            rs.close();
            smt.close();*/
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_spisakRadovaAutoraMouseClicked

    private void setTableData() {
        try {
            int rows = 0;
            int rowIndex = 0;
            
            Object objAutori = cbAutor.getSelectedItem();
            autor_id = objAutori.toString();
            
            Statement smt = conn.createStatement();
            /*ResultSet rs = smt.executeQuery("SELECT rad_recezent.rad_recezent_id, IF(SUM(rad_recezent.odluka = 1) > 2, radovi.rb_sveske, 'Nije prihvacen') , "
                    + "radovi.naziv, rad_recezent.datum_slanja_recenzije, rad_recezent.datum_dobijanja_recenzije, "
                    + "rad_recezent.odluka FROM radovi INNER JOIN rad_recezent ON "
                    + "radovi.rad_id = rad_recezent.rad_id WHERE rad_recezent.recezent_id ="+idRecezent(recezent_id));*/
            ResultSet rs = smt.executeQuery("SELECT autori_radovi.autori_radovi_id, autori_radovi.rad_id,"
                    + "radovi.naziv FROM radovi INNER JOIN autori_radovi ON "
                    + "radovi.rad_id = autori_radovi.rad_id WHERE autori_radovi.autor_id ="+idAutor(autor_id));
            if (rs.next()) {
                rs.last();
                rows = rs.getRow();
                rs.beforeFirst();
            }
            
            String[][] data = new String[rows][3];
            while(rs.next())
            {
                data[rowIndex][0] = rs.getInt(1)+"";
                data[rowIndex][1] = rs.getString(3);
                data[rowIndex][2] = String.valueOf(brojOdobrenih(rs.getInt(2)));
                rowIndex++;
            }
            String[] cols = {"ID", "Rad", "Status"};
            
            DefaultTableModel model = new DefaultTableModel(data, cols);
            spisakRadovaAutora.setModel(model);
            
            rs.close();
            smt.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ne mogu se popuniti podaci..."+ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAutor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable spisakRadovaAutora;
    // End of variables declaration//GEN-END:variables
}
